### PR TITLE
Blender 3+ Conversion

### PR DESCRIPTION
**Pull request by alistairpt**
Forming synapses should work in Blender 3.1 with the changes to synapseformerview.py.
Also fixed a few minor issues I encountered.

### CODE REVIEW

**Comment by JustasB** [comment]
Hi @alistairpt , The PR looks great!

If you haven't already, you can check if the rest of the BN codebase works correctly by running the test suite in this file:
https://github.com/JustasB/BlenderNEURON/blob/master/test.sh#L4

**Comment by alistairpt** [comment]
Hi @JustasB, I ran the tests you suggested, and with the changes here test_synapse_former runs without issue.

The only other errors I'm getting are from test_layer_confinement and an error in test_cell_import_export.
I'll take a look at those next!

**Comment by alistairpt** [comment]
Confining to layers works when trying it in Blender. However the resulting section locations/angles are slightly different than they were before Blender 3, which is causing test_layer_confinement.py to report an error (Running the test file gives discrepencies between 0.03 and 5). But I can't decide if that's an issue or if I should just modify the test since it still succesfully confines sections between layers.

**Comment by JustasB** [comment]
Hi @alistairpt , I added the `.circleci/config.yml` file and updated a few others related to installing blenderneuron in CI builds. 

It will now use the Circle CI system to build commits to the PR. E.g. can see the latest commit build results here: https://app.circleci.com/pipelines/github/JustasB/BlenderNEURON/23/workflows/747333e3-ab13-4bb8-94a7-9ba341ee0b27/jobs/23

There is some issue with coverage. It shows the coverage is much lower (77%) than the one on the master branch (91% - can be seen on the github repo home page). As far as I can tell, it's still running the tests, but for some reason coverage data is not getting collected. I'll take a closer look to see what's missing.

**Comment by JustasB** [comment]
Hi @alistairpt ,

There is an issue with the CI build system where it doesn't auto-trigger builds when commits are pushed into this PR.

I suspect this might be because the PR is from your fork to `BlenderNEURON\blender-3-plus-conversion` branch.

Let me try merging the PR into `BlenderNEURON\blender-3-plus-conversion` branch. 

If this works, I'll open a new PR to merge your changes from `BlenderNEURON\blender-3-plus-conversion ` into `BlenderNEURON\master` (the main branch). I've made you a collaborator in BlenderNEURON repo, so you should be able to pull down changes from the `BlenderNEURON\blender-3-plus-conversion` branch and then continue to work in that branch.

**Pull request merged**
